import bcrypt from 'bcrypt';

const SALT_ROUNDS = 12;

export function isBcryptHash(value) {
  // Recognise complete bcrypt hashes so restarting cannot double-hash them.
  return typeof value === 'string' && /^\$2[ab]\$(0[4-9]|[12][0-9]|3[01])\$[./A-Za-z0-9]{53}$/.test(value);
}

export function validCredentials(username, password) {
  // bcrypt only uses the first 72 bytes. Reject longer new passwords/logins
  // instead of silently treating different passwords as the same password.
  return typeof username === 'string' && username.trim().length > 0
    && typeof password === 'string' && password.length > 0
    && Buffer.byteLength(password, 'utf8') <= 72;
}

export async function hashPassword(password) {
  if (typeof password !== 'string' || Buffer.byteLength(password, 'utf8') > 72) {
    throw new Error('Password must be a string of at most 72 UTF-8 bytes.');
  }
  // The salt is generated by bcrypt and included in the stored hash.
  return bcrypt.hash(password, SALT_ROUNDS);
}

export function publicUser(user) {
  const { password, _id, ...safeUser } = user;
  return safeUser;
}

export async function migratePasswords(users) {
  for await (const user of users.find({})) {
    if (isBcryptHash(user.password)) continue;
    const hash = await hashPassword(user.password);
    // Match the old value too: another process may already have migrated it.
    await users.updateOne(
      { _id: user._id, password: { $eq: user.password } },
      { $set: { password: hash } }
    );
  }
}
